### ISSUE TITLE
Refactoring on using RestClient instead of RestTemplate

### ISSUE THREAD

**Issue by StefanSchubert** [StefanSchubert/sabi#138]
According to spring documentation RestTemplate is in maintenance only mode. I suppose it will be marked as deprecated sooner or later. ( Check "NOTE" in its documentation: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html )

Meanwhile the Project is on SpringBoot3.2 which brings in the RestClient as an alternative to the WebClient. 
See https://youtu.be/UDNrJAvKc0k

Which seems the appropriate successor. It comes with a fluent API and offers more flexibility through the extensibility by adding Interceptors as well.

**Comment by AKARSHITJOSHI** [comment]
Hi @StefanSchubert I would like to contribute on this. Let me know where to get started.

**Comment by StefanSchubert** [comment]
Hi @AKARSHITJOSHI,

thanks for reaching out. You are the first contributor here, so your first step would be to do the review on setting up the software development environment. ;-) For doing so, you need to follow the section: "Setting up the development environment" from the main README.md of the repository. Let me know if you stuck somewhere.

Have also a look onto the contribution.md guide.

Once the local setup was successful you have the modules available for testing, see section 3.2 from https://github.com/StefanSchubert/sabi/wiki/03.-System-Scope-and-Context 

for the task you require to draw your attention towards the frontend module (sabi-webclient) first. The package de.bluewhale.sabi.webclient.apigateway containts the RestTemplate communication which needs to be replaced accordingly. There are currently no junits on the frontend module, so you need to do an explorative testing locally. 

Once this task is finished, the attention should go to the backend module, which uses restTeamplate to communicate with the captcha module and there are some junits to demonstrate the api usage which are also based on the resttemplate.

By the way, do you have a fish tank? Or are you just technically interested (which is also fine :-) )

**Comment by StefanSchubert** [comment]
Hi @AKARSHITJOSHI,
as I haven't heard anything from you since then. I'm going to rewrite the Issue as meanwhile we are on SpringBoot3.2 and this brought us the new RestClient which is a better solution for this purpose. 
Let me know if you still have interest and time to contribute.

**Comment by StefanSchubert** [comment]
Merged to DevelopBranch
