### ISSUE TITLE
Broken Project Statistics (user count)

### ISSUE THREAD

**Issue by StefanSchubert** [StefanSchubert/sabi#141]
Observed after Service Release.

To reproduce: login and jump in the menu to projects statistics. You will See N/A as user count and the following in the log:

java.lang.NullPointerException: Cannot invoke "de.bluewhale.sabi.services.UserService.fetchAmountOfParticipants()" because "this.userService" is null

**Comment by SinyukKirill** [comment]
Hello. I'd like to work on this issue
